name: Nein
favicon: null
layout_spectrum: 0.9460785021074116
typography_spectrum: 0.9148486924823374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#f4f4f4'
    - '#bfbfbf'
    - '#494949'
    - '#737373'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
